### ISSUE TITLE
'sys' is not defined

### ISSUE THREAD

**Issue by jeff-pal** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#1]
In linux ubuntu I got the error showed in the image below:
![image](https://user-images.githubusercontent.com/49883011/122415949-b4ac5380-cf5e-11eb-9cc2-911bcff814df.png)

**Solution**: I fixed it adding the following import line in the beginning of the `ETL_coletar_dados_e_gravar_BD.py` file:
`import sys`

**Comment by aphonsoar** [comment]
Thank you @jeff-pal ! Solved by this commit: https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/commit/95fbb3bbb2d474053793caaa08dc4629d7c28871
