### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

### ISSUE THREAD

**Issue by ronaldopadula** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#10]
Eu criei uma pasta chamada download dentro da pasta code. E eu uso ubuntu. Verifiquei que há um erro na forma de colocar este diretório. Eu uso ubuntu.

no .env coloquei da seguinte forma:

OUTPUT_FILES_PATH=download
EXTRACTED_FILES_PATH=download

está correto?

daí segui o seguinte:

(base) ronaldo@rpo:~/Área de Trabalho/cnpj/code$ python ETL_coletar_dados_e_gravar_BD.py

F.K03200$W.SIMPLES.CSV.D10814.zip
F.K03200$Z.D10814.CNAECSV.zip
F.K03200$Z.D10814.MOTICSV.zip
F.K03200$Z.D10814.MUNICCSV.zip
F.K03200$Z.D10814.NATJUCSV.zip
F.K03200$Z.D10814.PAISCSV.zip
F.K03200$Z.D10814.QUALSCSV.zip
K3241.K03200Y0.D10814.EMPRECSV.zip
K3241.K03200Y0.D10814.ESTABELE.zip
K3241.K03200Y0.D10814.SOCIOCSV.zip
K3241.K03200Y1.D10814.EMPRECSV.zip
K3241.K03200Y1.D10814.ESTABELE.zip
K3241.K03200Y1.D10814.SOCIOCSV.zip
K3241.K03200Y2.D10814.EMPRECSV.zip
K3241.K03200Y2.D10814.ESTABELE.zip
K3241.K03200Y2.D10814.SOCIOCSV.zip
K3241.K03200Y3.D10814.EMPRECSV.zip
K3241.K03200Y3.D10814.ESTABELE.zip
K3241.K03200Y3.D10814.SOCIOCSV.zip
K3241.K03200Y4.D10814.EMPRECSV.zip
K3241.K03200Y4.D10814.ESTABELE.zip
K3241.K03200Y4.D10814.SOCIOCSV.zip
K3241.K03200Y5.D10814.EMPRECSV.zip
K3241.K03200Y5.D10814.ESTABELE.zip
K3241.K03200Y5.D10814.SOCIOCSV.zip
K3241.K03200Y6.D10814.EMPRECSV.zip
K3241.K03200Y6.D10814.ESTABELE.zip
K3241.K03200Y6.D10814.SOCIOCSV.zip
K3241.K03200Y7.D10814.EMPRECSV.zip
K3241.K03200Y7.D10814.ESTABELE.zip
K3241.K03200Y7.D10814.SOCIOCSV.zip
K3241.K03200Y8.D10814.EMPRECSV.zip
K3241.K03200Y8.D10814.ESTABELE.zip
K3241.K03200Y8.D10814.SOCIOCSV.zip
K3241.K03200Y9.D10814.EMPRECSV.zip
K3241.K03200Y9.D10814.ESTABELE.zip
K3241.K03200Y9.D10814.SOCIOCSV.zip
Arquivos que serão baixados:
1 - F.K03200$W.SIMPLES.CSV.D10814.zip
2 - F.K03200$Z.D10814.CNAECSV.zip
3 - F.K03200$Z.D10814.MOTICSV.zip
4 - F.K03200$Z.D10814.MUNICCSV.zip
5 - F.K03200$Z.D10814.NATJUCSV.zip
6 - F.K03200$Z.D10814.PAISCSV.zip
7 - F.K03200$Z.D10814.QUALSCSV.zip
8 - K3241.K03200Y0.D10814.EMPRECSV.zip
9 - K3241.K03200Y0.D10814.ESTABELE.zip
10 - K3241.K03200Y0.D10814.SOCIOCSV.zip
11 - K3241.K03200Y1.D10814.EMPRECSV.zip
12 - K3241.K03200Y1.D10814.ESTABELE.zip
13 - K3241.K03200Y1.D10814.SOCIOCSV.zip
14 - K3241.K03200Y2.D10814.EMPRECSV.zip
15 - K3241.K03200Y2.D10814.ESTABELE.zip
16 - K3241.K03200Y2.D10814.SOCIOCSV.zip
17 - K3241.K03200Y3.D10814.EMPRECSV.zip
18 - K3241.K03200Y3.D10814.ESTABELE.zip
19 - K3241.K03200Y3.D10814.SOCIOCSV.zip
20 - K3241.K03200Y4.D10814.EMPRECSV.zip
21 - K3241.K03200Y4.D10814.ESTABELE.zip
22 - K3241.K03200Y4.D10814.SOCIOCSV.zip
23 - K3241.K03200Y5.D10814.EMPRECSV.zip
24 - K3241.K03200Y5.D10814.ESTABELE.zip
25 - K3241.K03200Y5.D10814.SOCIOCSV.zip
26 - K3241.K03200Y6.D10814.EMPRECSV.zip
27 - K3241.K03200Y6.D10814.ESTABELE.zip
28 - K3241.K03200Y6.D10814.SOCIOCSV.zip
29 - K3241.K03200Y7.D10814.EMPRECSV.zip
30 - K3241.K03200Y7.D10814.ESTABELE.zip
31 - K3241.K03200Y7.D10814.SOCIOCSV.zip
32 - K3241.K03200Y8.D10814.EMPRECSV.zip
33 - K3241.K03200Y8.D10814.ESTABELE.zip
34 - K3241.K03200Y8.D10814.SOCIOCSV.zip
35 - K3241.K03200Y9.D10814.EMPRECSV.zip
36 - K3241.K03200Y9.D10814.ESTABELE.zip
37 - K3241.K03200Y9.D10814.SOCIOCSV.zip
Baixando arquivo:
1 - F.K03200$W.SIMPLES.CSV.D10814.zip
Downloading: 100% [158240034 / 158240034] bytes - Traceback (most recent call last):
  File "ETL_coletar_dados_e_gravar_BD.py", line 72, in <module>
    wget.download(url, out=output_files, bar=bar_progress)
  File "/home/ronaldo/anaconda3/lib/python3.7/site-packages/wget.py", line 529, in download
    filename = outdir + "/" + filename
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

**Comment by hpgsantos** [comment]
Você pode adicionar **str** nas linhas 

#72

```
wget.download(url, out=str(output_files), bar=bar_progress)
```

```
wget.download(Layout, out=str(output_files), bar=bar_progress)
```

**Comment by ronaldopadula** [comment]
Gostaria de confirmar que essa alteração deu conta de resolver o meu problema.
