### ISSUE TITLE
psycopg2.OperationalError: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by ronaldopadula** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#11]
Bom, meu postgre está configurado pela por 5433, eu testei uma conexão com o banco de dados usando Rstudio por exemplo e foi tudo certo. Não há problemas no banco. Mas com esse código não consigo.

No .env inseri as seguintes info de teste

DB_HOST=localhost
DB_PORT=5433
DB_USER=cnpj_user
DB_PASSWORD=senhaqualquer
DB_NAME=cnpj_rfb

Todos estes dados estão funcionando corretamente mas, dá sempre o seguinte erro:

psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

**Comment by aphonsoar** [comment]
Novos testes foram feitos e nao ha problema no projeto, isso deve ser alguma configuracao da maquina local. Vou encerrar essa issue, caso ainda tenha mais duvidas, ou o link acima nao tenha resolvido, fique a vontade em compartilhar por aqui. Obrigado.
