### ISSUE TITLE
Onde fica o dir code?

### ISSUE THREAD

**Issue by ricardo-1908** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#12]
Olá estou seguindo o tutorial mas não sei onde colocar o diretorio ou onde fica o diretório **code** , onde devo colocar o arquivo .env com minhas opções. Pode me ajudar?
Obrigado.

**Comment by aphonsoar** [comment]
Subi ha pouco um commit com algumas correcoes no codigo para Windows 10 - atualizei o [README](https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/blob/master/README.md) com mais detalhes de como criar o arquivo `.env` e deixar o processo mais claro. 

Detalhes aqui: [commit](https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/commit/67e05ffb278176bde6ed885860c39955816550d6). 

Obrigado.
