### ISSUE TITLE
Erro em Wget.dowload

### ISSUE THREAD

**Issue by tutalucena** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#14]
Boa tarde pessoal! Ao corrigir o erro do .env, o código ao ser rodado apresentou o seguinte erro:
![erro](https://user-images.githubusercontent.com/74742050/141502691-e6ae5dc8-e0ac-4ebc-8562-d30aad967be7.PNG)
Por favor, peço ajuda esse código vai me ajudar muito!

**Comment by marcelo-franceschini** [comment]
Boa tarde @tutalucena.
Cara, vamos por partes:
- Vi que você já tem um issue aberto. Na próxima vez, responda no mesmo issue. Assim não teremos vários para o mesmo assunto.
- Não quero ser grosso ou cruel, mas se você quer executar um script python, é recomendável que você conheça um pouco da linguagem. Você domina python? Você ta utilizando uma IDE bem poderosa (eu particularmente acho até meio pesada e lerda. Mas isso é pessoal). Você já tentou debugar? Se você debugar você vai conseguir ver o que está acontecendo na linha que aponta o erro. Ele está tentando concaternar dois datatypes diferentes. TALVEZ um `str(Path(getEnv('OUTPUT_FILES_PATH')))` funcione
- Você tentou googlar o erro antes de postar aqui (novamente, não quero ser grosso)
- Você configurou o arquivo `.env` corretamente? Porque pelo que eu to vendo aqui, o scrpit tentou baixar direto na pasta raiz do script. É isso mesmo que você quer? O ideal é ter uma para para os zips e para on unzipeds
- Se quiser colocar uma foto do seu arquivo .env, não se acanhe, muito provavelmente seu db é apenas localhost, então não há perigo em compartilhar seu login e senha (mas você pode ocultar essa parte pelo paint se quiser. Aproveita que eu fechei minha sprint hoje e to com tempo livre e bom humor rs)

**Comment by marcelo-franceschini** [comment]
Se conseguir resolver, feche os issues, por gentileza. Só pra facilitar a vida do pessoal que mantém o código. Eu só dei clone no repo e to recebendo no e-mail esses issues bobos kkkk vai entender

**Comment by tutalucena** [comment]
Boa tarde, Segue apontamentos:
-Vi que você já tem um issue aberto. Na próxima vez, responda no mesmo issue. Assim não teremos vários para o mesmo assunto.
--Ok, vou fechar os issue assim que resolver.
-Não quero ser grosso ou cruel, mas se você quer executar um script python, é recomendável que você conheça um pouco da linguagem. Você domina python?
--Não há porque ser grosso eu apenas estou tentando entender,vou ser sincero com você, sou analista de dados, me deram uma atividade fora do meu campo de atuação eu uso python sim porém com foco em outras coisas, de fato tenho muita dificuldade para entender o seu código. Estou fazendo o melhor que eu posso.
- Você ta utilizando uma IDE bem poderosa (eu particularmente acho até meio pesada e lerda. Mas isso é pessoal). Você já tentou debugar? Se você debugar você vai conseguir ver o que está acontecendo na linha que aponta o erro. Ele está tentando concaternar dois datatypes diferentes. TALVEZ um str(Path(getEnv('OUTPUT_FILES_PATH'))) funcione
--Eu não consegui entender o erro apontado pelo debug, vou tentar isso que sugeriu.Você tentou googlar o erro antes de postar aqui (novamente, não quero ser grosso)Sim.Você configurou o arquivo .env corretamente? Porque pelo que eu to vendo aqui, o scrpit tentou baixar direto na pasta raiz do script. É isso mesmo que você quer? O ideal é ter uma para para os zips e para on unzipeds
--Sim, eu percebi que ele não baixou lá eu não entendi pq isso ocorreu. Aparentemente consegui configurar corretamente.Se quiser colocar uma foto do seu arquivo .env, não se acanhe, muito provavelmente seu db é apenas localhost, então não há perigo em compartilhar seu login e senha (mas você pode ocultar essa parte pelo paint se quiser. Aproveita que eu fechei minha sprint hoje e to com tempo livre e bom humor rs).
-Agradeço, farei isso!

> Se conseguir resolver, feche os issues, por gentileza. Só pra facilitar a vida do pessoal que mantém o código. Eu só dei clone no repo e to recebendo no e-mail esses issues bobos kkkk vai entender

![erro_](https://user-images.githubusercontent.com/74742050/141512212-13a59fb4-c4eb-4cfe-890a-50a7df08ad5b.PNG)

**Comment by marcelo-franceschini** [comment]
Evite criar diretórios com espaço. Coloca aspas nos diretórios ou muda para `TesteRF`.
Tenta de novo e posta aqui. Tmj

**Comment by marcelo-franceschini** [comment]
`OUTPUT_FILES_PATH=C:/diretoriosemespaço`
ou
`OUTPUT_FILES_PATH="C:/diretorio com espaço"`


> entender o seu código


O código não é meu :)

**Comment by marcelo-franceschini** [comment]
Outra dica que eu posso te dar:
O site da receita costumava ser MUITO lerdo pra baixar. Faz tempo que não baixo, não sei como tá hoje. Esse script é zero performático para download pois não é multithread (vai baixar um por um). Se eu fosse você, baixava tudo pelo Chrome, extraia, e apagava a parte de download e unzip do script.

**Comment by tutalucena** [comment]
> Evite criar diretórios com espaço. Coloca aspas nos diretórios ou muda para `TesteRF`. Tenta de novo e posta aqui. Tmj



> `OUTPUT_FILES_PATH=C:/diretoriosemespaco` ou `OUTPUT_FILES_PATH="C:/diretorio com espaco"`
> 
> > entender o seu código
> 
> O código não é meu :)

Eu eliminei o espaço e não deu certo, depois adicionei aspas, e mesmo assim ele faz o dowload dos arquivos no diretório do código =( 
![erro_](https://user-images.githubusercontent.com/74742050/141515306-d028697c-2f52-4359-be2c-0290d892b8af.PNG)

**Comment by marcelo-franceschini** [comment]
Espera o download terminar. Aparentemente wget primeiro vai baixaar na pasta raiz do script e depois irá mover para a pasta setada no parâmetro `out`.

Baixando:
![image](https://user-images.githubusercontent.com/34426867/141516205-91189c46-c2a3-4b28-abcb-01af9f054c5f.png)

Depois de concluído:
![image](https://user-images.githubusercontent.com/34426867/141517505-d7f768a5-6dac-4ab3-823b-a9b0196dff56.png)



Mas novamente, se eu fosse você baixava pelo Chrome vários ao mesmo tempo, pois o servidor da RBF ainda está em 1999 aparentemente:
![image](https://user-images.githubusercontent.com/34426867/141516637-557f63bb-6d34-4185-ab5b-7e123078633d.png)

**Comment by tutalucena** [comment]
@marcelo-franceschini vou aguardar o download finalizar e lhe informo. Independente de dar certo, ou não, eu agradeço ai a sua disponibilidade em me ajudar.
Vou baixar as pastas pelo Chrome mesmo para depois fazer as tratativas, demora muito mesmo.

**Comment by tutalucena** [comment]
@marcelo-franceschini Após o dowload o debug retornou o seguinte apontamento, não consegui entender...
![erro_](https://user-images.githubusercontent.com/74742050/141522572-db086353-c2ef-43dd-b170-1c36637b6bf6.PNG)

**Comment by marcelo-franceschini** [comment]
Desculpa a demora. Troca as linha 25 e 26 de:
`output_files = Path(getEnv('OUTPUT_FILES_PATH'))
extracted_files = Path(getEnv('EXTRACTED_FILES_PATH'))`
para:
`output_files = str(Path(getEnv('OUTPUT_FILES_PATH')))
extracted_files = str(Path(getEnv('EXTRACTED_FILES_PATH')))`
e apaga a parte de download. Acho que é da linha 63 a 78.

**Comment by tutalucena** [comment]
@marcelo-franceschini eu que tenho que pedir desculpas pela série de dúvidas kkk
Fiz o correção e ele salvou os arquivos na pasta que designei! Achei que daria tudo certo, porém na hora de criar os índices travou novamente, segue o DEBUG:
![erro_](https://user-images.githubusercontent.com/74742050/141660262-3984765d-440c-41ae-93f0-8d2125082a02.PNG)

**Comment by tardoproto** [comment]
Tive o mesmo problema original do @tutalucena e a solução proposta por @marcelo-franceschini , de simplesmente incluir um "str" antes de "(Path(getEnv('OUTPUT_FILES_PATH')))", na linha 25, funcionou. 

`str(Path(getEnv('OUTPUT_FILES_PATH')))`

Muito obrigado!

Estou usando Windows 10 (sei que não é o ideal, mas faz tempo que não tenho uma segunda máquina para Linux) e Thonny (Python 3.7). 

E aproveito para agradecer e parabenizar @aphonsoar

**Comment by aphonsoar** [comment]
Eu tambem enfrentei o problema no wget e na definicao dos paths. com isso, subi ha pouco um commit com algumas correcoes no codigo para Windows 10 - a definicao do objeto como tipo `WindowsPath` estava causando problema, eh melhor deixar como `string` mesmo. Testei o processo end-to-end aqui e agora funcionou perfeitamente, detalhes aqui: [commit](https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/commit/67e05ffb278176bde6ed885860c39955816550d6). 

Com isso, entendo que o problema reportado nessa issue (erro no wget e path) ficou solucionado.

@tardoproto, conseguiu resolver este outro problema de encoding que vc enfrentou?

**Comment by Rodrigojxj** [comment]
@tardoproto Tive o mesmo problema, como resolveu?

**Comment by aphonsoar** [comment]
@Rodrigojxj vc clonou o projeto novamente? Eu subi um commit em Abril que aparentemente resolveu isso - pra mim funcionou 100%
