### ISSUE TITLE
Download congelado

### ISSUE THREAD

**Issue by abobre** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#15]
Segui todos os passos informados, porem ele congela no arquivo 09

**9 - K3241.K03200Y0.D11009.ESTABELE.zip
Downloading: 6% [36741120 / 553078659] bytes -**

Já tentei várias vezes mas sempre fica assim!

**Comment by aphonsoar** [comment]
Oi Andre.

Isso eh estranho, porque nao faz sentido do ponto de vista do programa. Isso deve ser problema ou na sua conexao ou - provavelmente - no host (site da Receita Federal).

Vc tentou em dias diferentes? Talvez seja alguma instabilidade do servidor da RFB.

**Comment by rictom** [comment]
Se procurar em http://200.152.38.155/CNPJ/ tem os arquivos atualizados em novembro, enquanto a página https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj aponta para arquivos antigos (e que não baixam)

**Comment by aphonsoar** [comment]
Atualizei os dados hoje (24/04/22), utilizando o diretorio http://200.152.38.155/CNPJ/ e os arquivos estao funcionando corretamente.
