### ISSUE TITLE
Sistema Web para consultar os dados

### ISSUE THREAD

**Issue by bjverde** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#16]
Pessoal, usando o modelo de banco desse projeto e carga em Python criei uma aplicação web PHP para facilitar a consulta de pessoas sem grande conhecimento de consulta SQL. Espero que seja útil , mais uma vez quero agradecer todos que contribuíram de forma direta ou indireta 

https://github.com/bjverde/cnpjrfb

![image](https://user-images.githubusercontent.com/1070062/145756267-e6576710-cc23-449f-bd36-929f00e7df2d.png)

**Comment by aphonsoar** [comment]
Sensacional @bjverde, obrigado pela mencao e por compartilhar!
