### ISSUE TITLE
Incluir o arquivo requirements.txt para instalação das dependências.

### ISSUE THREAD

**Issue by hideraldus13** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#2]
Incluir o arquivo requirements.txt para instalação das dependências.

**Comment by aphonsoar** [comment]
Resolvido cfe https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/pull/3
