### ISSUE TITLE
Erro no Path

### ISSUE THREAD

**Issue by gustavokubiack** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#22]
Não estou conseguindo identificar o erro do path.

O erro ao executar:
![image](https://user-images.githubusercontent.com/86686830/164695589-672d0a9d-518b-4970-abdf-1a312e9996bc.png)

O .env_template: 
![image](https://user-images.githubusercontent.com/86686830/164696660-52ba3054-0e56-4ca3-a404-8f01a5343c39.png)

**Comment by aphonsoar** [comment]
@jeff-pal consegue identificar o que esta acontecendo? Dei uma olhada mas nao encontrei o problema

**Comment by aphonsoar** [comment]
@gustavokubiack, subi ha pouco um commit com algumas correcoes no codigo para Windows 10. Testei o processo end-to-end aqui e agora funcionou perfeitamente, veja os detalhes nesse [commit](https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/commit/67e05ffb278176bde6ed885860c39955816550d6).

Sugiro que vc clone o projeto de novo, nessa nova versao, e refaca o teste, por favor. Qualquer duvida pode responder por aqui.

Obrigado,
Abs.

**Comment by gustavokubiack** [comment]
@aphonsoar clonei o projeto novamente, e coloquei pra rodar o código. Os arquivos foram baixados normalmente, mas na hora de criar um diretório para armazenar os arquivos extraídos (linha 98), está dizendo que o path é NoneType. Consegue identificar onde estou errando?

Erro: 
![image](https://user-images.githubusercontent.com/86686830/164981554-a64dfa07-ed8a-41f1-9d99-f71668f94228.png)

.env:
![image](https://user-images.githubusercontent.com/86686830/164981575-3f1a4587-2250-4378-8b96-57693de1cf3c.png)

**Comment by aphonsoar** [comment]
Entendi o seu problema @gustavokubiack. Acredito que com o update do seu comentario, o caso esta resolvido, certo? Obrigado por compartilhar.
