### ISSUE TITLE
Erro 

### ISSUE THREAD

**Issue by Rodrigojxj** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#23]
![Captura de Tela (35)](https://user-images.githubusercontent.com/42561258/170707472-707cf61e-943b-4a27-9a39-dcf855dbaf6d.png)

Recebi esse erro ao executar.

**Comment by Rodrigojxj** [comment]
@aphonsoar Consegui avançar, todo o código funciona, com exceção na criação da tabela de estabelecimentos, tive problema de memória e fiz como na tabela do SIMPLES, dividindo em 10 partes, porém ao iniciar o segundo arquivo, tenho um erro de unicode. 
![image](https://user-images.githubusercontent.com/42561258/171868532-daedc060-ba8e-425c-9ae1-cfb732cf4dee.png)

**Comment by GleisonSette** [comment]
@Rodrigojxj Você conseguiu resolver. Estou com o mesmo problema.

**Comment by GleisonSette** [comment]
@Rodrigojxj e demais que irão ler. Solucionei conforme issue respondido:

https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/issues/21

**Comment by Rodrigojxj** [comment]
@GleisonSette Consegui solucionar mundando de r para rb na leitura do arquivo deixei open(extracted_file_path, "rb")). Estou com a base de dados no computador funcionado.

**Comment by GleisonSette** [comment]
Vlw @Rodrigojxj
