### ISSUE TITLE
Lentidão no acesso ao servidor

### ISSUE THREAD

**Issue by pedroroccon** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#25]
Pessoal, é normal para vocês a lentidão no acesso no servidor dos dados públicos da receita? Não consigo acessar o endereço http://200.152.38.155/CNPJ nem pelo navegador

**Comment by karlosmorais** [comment]
> Pessoal, é normal para vocês a lentidão no acesso no servidor dos dados públicos da receita? Não consigo acessar o endereço http://200.152.38.155/CNPJ nem pelo navegador

Ola Pedro. Baixei os arquivos ontem e percebi essa lentidão. Mas pelo meu conhecimento é normal, devido  quantidade de acesso, e ambiente.

**Comment by hcs-bernardo-rufino** [comment]
@pedroroccon, é normal sim, sugiro fazer download no período noturno ou então de madrugada.
