### ISSUE TITLE
Dados Restritos

### ISSUE THREAD

**Issue by noobandrew** [aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ#37]
Olá, não sei se é pra ser assim, mas ao clicar no "https://www.gov.br/receitafederal/acl_users/credentials_cookie_auth/require_login?came_from=https%3A//www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj" sem nenhum procedimento anterior, aparece isso: 
![image](https://user-images.githubusercontent.com/110668566/227209403-9a26a4eb-a10e-4ec1-b4be-266537495192.png)

É normal?

**Comment by aphonsoar** [comment]
Isso esta acontecendo porque a Receita Federal mudou o link da pagina que descrevia os dados. No entanto essa pagina eh apenas informativa, o FTP onde os arquivos estao disponiveis permanece no mesmo local, onde o codigo tambem esta apontando. Aqui: http://200.152.38.155/CNPJ/

**Comment by aphonsoar** [comment]
A saber, esse eh o link novo. Vou atualizar o README. https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-jurdica---cnpj

**Comment by aphonsoar** [comment]
Resolvido cfe descrito acima e commit https://github.com/aphonsoar/Receita_Federal_do_Brasil_-_Dados_Publicos_CNPJ/commit/a40504276d21dfada4f6dc43c8b7920e6ad292d6.
